# Generated by Django 5.2 on 2025-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='missing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
