# Generated by Django 5.2 on 2025-04-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shipmentitem_missing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='status',
        ),
    ]
