# Generated by Django 5.2 on 2025-04-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shipment_created_at_shipment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.shipment'),
            preserve_default=False,
        ),
    ]
