# Generated by Django 5.1.6 on 2025-05-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_shipmentitem_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='missing',
        ),
    ]
