# Generated by Django 5.1.6 on 2025-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_shipmentitem_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='missing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
